In [23]:
import h5py
import pptk
import pandas as pd
import numpy as np

In [3]:
f = h5py.File('ply_data_train1.h5', 'r')

In [4]:
list(f.keys())

['data', 'faceId', 'label', 'normal']

In [6]:
data = f['data']
data

<HDF5 dataset "data": shape (2048, 2048, 3), type "<f4">

In [8]:
face = f['faceId']
face

<HDF5 dataset "faceId": shape (2048, 2048), type "<i4">

In [9]:
label = f['label']
label

<HDF5 dataset "label": shape (2048, 1), type "|u1">

In [10]:
normal = f['normal']
normal

<HDF5 dataset "normal": shape (2048, 2048, 3), type "<f4">

In [11]:
data[0]

array([[-0.19995758, -0.00575545,  0.6151126 ],
       [-0.28962055, -0.48679873, -0.7802458 ],
       [-0.32760182, -0.4277147 , -0.7982146 ],
       ...,
       [ 0.1053436 ,  0.22563282, -0.72715074],
       [ 0.21908867, -0.02505763, -0.6966349 ],
       [-0.00767022, -0.15380809, -0.84131134]], dtype=float32)

In [14]:
v = pptk.viewer(data[1])

In [18]:
face[0]

array([294, 388, 382, ...,  29, 109,  58])

In [16]:
label[0]

array([12], dtype=uint8)

In [21]:
df = pd.read_csv('Training/5_SMV_chapel_1.txt', sep=' ', header=None)
df.head()

0            1           2    3    4    5  6         7         8  \
0  204.054230  4269.843750  598.618958  255  255  255  9  0.870893 -0.300466   
1  203.960236  4270.003906  598.746948  253  254  254  9  0.729889 -0.491558   
2  203.868225  4269.674805  598.414978  103  109  152  9 -0.338886 -0.809825   
3  204.695236  4270.380859  598.420959  120  107  133  9  0.356974  0.738397   
4  203.965225  4269.679688  598.505920  152  157  177  9  0.778842 -0.616890   

          9  
0  0.388928  
1  0.475007  
2  0.478895  
3 -0.572136  
4 -0.113366

In [26]:
points = np.array(df[[0, 1, 2]])
colors = np.array(df[[3, 4, 5]])
classes = np.array(df[6])
normals = np.array(df[[7, 8, 9]])

In [27]:
train1 = h5py.File('h5/train1.h5', 'w')

In [28]:
train1.create_dataset('data', data=points)

<HDF5 dataset "data": shape (3783412, 3), type "<f8">